maintainer        'Samsung SRA'
maintainer_email  'jeff.morgan@samsung workstation'
license           'MIT'
description       'Uses pivotal_workstation to configure an OSX workstation for development'
long_description  'Uses pivotal_workstation to configure an OSX workstation for development'
version           '0.1.0'
supports          'mac_os_x'

depends           'pivotal_workstation'
depends           'sprout-osx-settings'
depends           'sprout-osx-apps'
